disabled_rules: # rule identifiers to exclude from running
 - trailing_whitespace
 - unused_closure_parameter
 # - unused_optional_binding

opt_in_rules:
- empty_string

excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Carthage
 - Pods
 - SwiftLint/Common/3rdPartyLib
 
line_length:
  warning: 200
  error: 215
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 300
  error: 500

function_parameter_count:
  warning: 6
  error: 8

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 1000
  error: 1500
  ignore_comment_only_lines: true

cyclomatic_complexity:
  warning: 15
  error: 25

identifier_name:
  excluded:
    - id
    - q
    - to

reporter: "xcode"
